### PR TITLE
Fix Druid Mangle talent not teaching the Cat/Bear Spells

### LINKED ISSUE #55: Bug: Problem with Mangle talent
### Current Behaviour

The Feral Druid talent “Mangle” (ID 33917) does not teach players the spells Mangle (Cat) and Mangle (Bear) when it is learned through the template module.

I opened Spell.dbc to check the talent and found that Mangle (33917) and Feral Charge (49377) are talents that teach the player two spells each. Mangle teaches Mangle (Cat) and Mangle (Bear), and the Feral Charge talent teaches Feral Charge – Bear and Feral Charge – Cat.

These two talents have a spell attribute called “Cast when learned,” so when you learn them the talent automatically teaches you the two spells.

However, for some reason, when using the NPC talent template only the Feral Charge talent teaches both the talent and its two Charge spells; the Mangle talent does not teach the two Mangle spells.

I managed to make it work by manually adding the two spells (Mangle – Cat and Mangle – Bear) + the talent to the mod_npc_talent_template database. I don’t know if there are any other talents that work like this, but if anyone encounters the same problem, this is how you can fix it.

### Expected Behaviour

Mangle talent should teach the two spells Mangle(Cat) and Mangle(Bear) when selecting a talent template.

### Steps to reproduce the problem

1. Get a level 70 druid
2. Select the 'Feral Cat T6 PvE' template
3. Notice that even though you learn the talent, the Mangle spells are missing on your spellbook

### Extra Notes

_No response_

### AC rev. hash/commit

https://github.com/azerothcore/azerothcore-wotlk/commit/d5bee6e2a359

### Operating system

Windows 10 x64

### Custom changes or Modules

_No response_

### PR DESCRIPTION
**Pull request by laasker**
## Changes Proposed:
- Fixes druid talent 'Mangle', that was not teaching the Cat and Bear Mangle spells.
- Now, when using the druid template, it properly teaches the Mangle spell as well as the talent. It also teaches the highest rank of the spell according to the player's level.

## Issues Addressed:

- Closes https://github.com/azerothcore/mod-npc-talent-template/issues/55

## Tests Performed:

- Windows 10
- Tested ingame

## How to Test the Changes:

1. Get a level 70 druid
2. Speak to the template npc and select the level 70 PvE cat template
3. Notice that you now learn the Mangle spells and the spell rank is Rank 3(level 68) instead of Rank 5 (level 80).

### CODE REVIEW

File: src/npc_talent_template.cpp [hunk 1]
```diff
@@ -73,6 +74,26 @@ void sTemplateNPC::LearnTemplateTalents(Player* player, const std::string& sTale
         {
             player->learnSpellHighRank(talentTemplate->talentId);
             player->addTalent(talentTemplate->talentId, player->GetActiveSpecMask(), 0);
+
+            // Druid Mangle talent
+            if (talentTemplate->talentId == 33917)
```
Comment (Helias) [inline src/npc_talent_template.cpp]: it's not a blocker for the PR, but I would create an enum or better in this case a `#define DRUID_MANGLE 33917`, for avoiding magic numbers and improve the readability

File: src/npc_talent_template.cpp [hunk 2]
```diff
@@ -73,6 +74,26 @@ void sTemplateNPC::LearnTemplateTalents(Player* player, const std::string& sTale
...
+                    for (uint32 id = baseRankId; id; id = sSpellMgr->GetNextSpellInChain(id))
+                    {
+                        const SpellInfo* info = sSpellMgr->GetSpellInfo(id);
+                        if (!info || info->BaseLevel > player->GetLevel())
+                               break;
+                        player->learnSpell(id);
+                    }
+                };
+                LearnHighestRankForLevel(33876); // Mangle –  Cat
+                LearnHighestRankForLevel(33878); // Mangle –  Bear
```
Comment (Helias) [inline src/npc_talent_template.cpp]: same here, at this point, maybe it's better an enum to wrap all these spells names, and delete the comments

File: src/npc_talent_template.cpp (hunk 1 above)
Comment (laasker) [reply src/npc_talent_template.cpp]: > it's not a blocker for the PR, but I would create an enum or better in this case a `#define DRUID_MANGLE 33917`, for avoiding magic numbers and improve the readability

no worries, can you take a look now?

**Review by Helias — APPROVED** [review]

**Comment by Helias** [comment]
thanks!
